name: Client CI

on:
  push:
    branches: [master]
    paths-ignore: ["server/**", ".github/.workflows/ci-server.yml"]
  pull_request:
    branches: [master]
    paths-ignore: ["server/**", ".github/.workflows/ci-server.yml"]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1
      - run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - run: yarn install
      - run: yarn workspace client lint
      - run: yarn workspace client coverage
