name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
      BATECT_CACHE_TYPE: directory
      BATECT_ENABLE_TELEMETRY: true
    steps:
      - uses: actions/checkout@v2

      - name: Cache Batect
        uses: actions/cache@v2
        with:
          path: ~/.batect/cache
          key: batect-${{ hashFiles('batect') }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: .batect/caches
          key: batect-caches-new-${{ hashFiles('yarn.lock') }}

      - name: Download dependencies
        run: ./batect setup

  test-client:
    name: test-client
    needs: [setup]
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
      BATECT_CACHE_TYPE: directory
      BATECT_ENABLE_TELEMETRY: true

    steps:
      - uses: actions/checkout@v2

      - name: Cache Batect
        uses: actions/cache@v2
        with:
          path: ~/.batect/cache
          key: batect-${{ hashFiles('batect') }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: .batect/caches
          key: batect-caches-new-${{ hashFiles('yarn.lock') }}

      - name: Lint code
        run: ./batect client-lint

      - name: Unit tests
        run: ./batect client-coverage

  test-server:
    name: test-server
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2

      - name: Cache Batect
        uses: actions/cache@v2
        with:
          path: ~/.batect/cache
          key: batect-${{ hashFiles('batect') }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: .batect/caches
          key: batect-caches-new-${{ hashFiles('yarn.lock') }}

      - name: Lint code
        run: ./batect server-lint

      - name: Unit tests
        run: ./batect server-coverage
