name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: CultureHQ/actions-yarn@master
      with:
        args: install
    - name: Test
      uses: CultureHQ/actions-yarn@master
      with:
        args: workspace client test
